spring:
  application:
    name: ms-auth-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:123456@localhost:5050
jwt:
  secret: iOp3zJH32+HqbtXwUVzZB68NEmzmyY8aZuvjBQEiVhI=